import puppeteer, { type Browser } from "puppeteer";

/**
 * PDF Service — converts HTML strings to PDF buffers using headless Chromium via Puppeteer.
 *
 * Reuses the HTML generated by the AST → HTML transformer.
 * Ensures clean browser process management by always closing browser instances in a `finally` block.
 */
const pdfService = {
  /**
   * Renders an HTML string as a print-ready PDF buffer.
   *
   * @param html - Valid HTML5 document string
   * @returns Promise resolving to a PDF Buffer
   */
  async generatePdf(html: string): Promise<Buffer> {
    if (typeof html !== "string") {
      throw new Error("HTML content must be a string");
    }

    let browser: Browser | null = null;

    try {
      browser = await puppeteer.launch({
        headless: true,
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
        ],
      });

      const page = await browser.newPage();

      // Enable request interception to block local filesystem (file://) access
      await page.setRequestInterception(true);
      page.on("request", (interceptedReq) => {
        const url = interceptedReq.url().toLowerCase();
        if (url.startsWith("file:") || url.startsWith("ftp:") || url.startsWith("gopher:")) {
          interceptedReq.abort();
        } else {
          interceptedReq.continue();
        }
      });

      // Load HTML content into page with timeout
      await page.setContent(html, {
        waitUntil: "load",
        timeout: 10000,
      });

      // Generate PDF buffer with print settings
      const pdfUint8Array = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: {
          top: "20mm",
          right: "15mm",
          bottom: "20mm",
          left: "15mm",
        },
      });

      return Buffer.from(pdfUint8Array);
    } finally {
      if (browser !== null) {
        try {
          await browser.close();
        } catch (closeError: unknown) {
          console.error("Failed to close Puppeteer browser:", closeError);
        }
      }
    }
  },
};

export default pdfService;
